name: Update GHCR Packages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Packages from GHCR
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          echo "" > table.md
          echo "| Image Name | Repository | Last Updated |" >> table.md
          echo "| - | - | - |" >> table.md

          gh api "user/packages?package_type=container&?visibility=public" --jq '.[] | "| [\(.name)](\(.html_url)) | [\(.repository.name // "Package Repo")](\(.repository.html_url)) | \(.updated_at | split("T")[0]) |"' >> table.md
          
          echo "--- Tabla Generada ---"
          cat table.md

      - name: Insert table into README
        run: |
          sed -i 's/:pkg:START//g' README.md
          sed -i 's/:pkg:END//g' README.md
          
          sed -i '/pkg:START/,/pkg:END/{ /pkg:START/!{ /pkg:END/!d; }; }' README.md
          sed -i '/pkg:START/r table.md' README.md

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update ghcr packages list :pkg:" || exit 0
          git push