name: Update GHCR Packages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Packages from GHCR
        env:
          GH_TOKEN: ${{ secrets.GHUB_TOKEN }}
        run: |
          gh api /users/CrIsTiAnPvP/packages \
            -f package_type=container \
            --jq '.[] | "| \(.name) | [\(.repository.name // "N/A")](\(.repository.html_url // "#")) | \(.updated_at | split("T")[0]) |"' > table.md
            
          cat table.md

      - name: Insert table into README
        run: |
          sed -i '/:pkg:START/,/:pkg:END/{ /:pkg:START/!{ /:pkg:END/!d; }; }' README.md
          sed -i '/:pkg:START/r table.md' README.md

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update ghcr packages list :pkg:" || exit 0
          git push