name: Update GHCR Packages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Packages from GHCR
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          echo "" > table.md
          echo "[![GitHub Packages](https://img.shields.io/badge/GitHub%20Packages-ghcr.io-blue?style=flat-square&logo=github)](https://github.com/cristianpvp?tab=packages)" >> table.md
          echo "" >> table.md
          echo "| Image Name | Repository | Last Updated |" >> table.md
          echo "| - | - | - |" >> table.md

          gh api "user/packages?package_type=container&visibility=public" --jq 'sort_by(.updated_at) | reverse | .[0:5] | .[] | "| [\(.name)](\(.html_url)) | [\(.repository.name // "Package Repo")](\(.repository.html_url)) | \(.updated_at | split("T")[0]) |"' >> table.md
          
          echo "" >> table.md
          
      - name: Insert table
        run: |
          sed -i '/## ðŸ“¦ Container Registry (GHCR)/,/## ðŸš¢ DevOps & Orchestration/{ /## ðŸ“¦ Container Registry (GHCR)/!{ /## ðŸš¢ DevOps & Orchestration/!d; }; }' README.md
          sed -i '/## ðŸ“¦ Container Registry (GHCR)/r table.md' README.md
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update ghcr packages list :pkg:" || exit 0
          git push